name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run check
      - run: ./triangles.ts
      - uses: actions/upload-artifact@v4
        with:
          path: out.svg
